# Generated by Django 4.2.2 on 2023-06-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gre', '0003_category_learner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('score', models.IntegerField(max_length=100)),
                ('no_of_ques', models.IntegerField(max_length=100)),
            ],
        ),
    ]
