# Generated by Django 4.2.2 on 2023-06-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gre', '0004_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='data',
            field=models.JSONField(),
        ),
    ]
