# Generated by Django 4.2.2 on 2023-07-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gre', '0005_alter_quiz_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='no_of_ques',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='score',
            field=models.IntegerField(),
        ),
    ]
